FROM certbot/certbot:latest

WORKDIR /app

RUN apk add --no-cache openssh sshpass

VOLUME /etc/letsencrypt
COPY cli.ini /etc/letsencrypt/cli.ini

COPY hook.sh /app/hook.sh
RUN chmod +x /app/hook.sh

ENTRYPOINT certbot certonly --email ${EMAIL} -d ${DOMAIN}
